### ISSUE TITLE
setup() / settings() disentanglement feature edge case?

### ISSUE THREAD

**Issue by villares** [hx2A/py5generator#40]
I understand you might choose not to tackle this case... but it is a common idiom to to put `global` statements at the start of functions, and this seems to break the rule of having `size()` as the first thing...

![image](https://user-images.githubusercontent.com/3694604/132129612-70537bf3-4c0d-4b69-b74b-16cca5af7468.png)

(As I know what is going on I had no trouble reordering...)

**Comment by hx2A** [comment]
Hmmm, I should fix this, because it breaks the illusion of `setup()` being a real function and not something that is split into two.

As a workaround, you can switch the order of the `global` statement and the call to `size()`.

I don't think this will be a hard fix. Right now you can put `#` comments before the call to `size()` and it will work fine. There's no reason why `global` can't also work. However, py5 will need to reshuffle things and put the `global` statements in the `_py5_faux_setup()` function (that's what it is called internally). They should not end up in `_py5_faux_settings()` with `size()`. The reshuffling will require impact a few things...fixing this is achievable, and I'll work on it.

**Comment by hx2A** [comment]
This fix seems to work. Global statements that precede the call to `size()` get moved to the fake `setup()` function.

**Comment by hx2A** [comment]
The hard part here isn't dealing with the `global` statements, it is making sure that there are no misleading error messages. If I have this in a notebook cell:

```
x = 10

def setup():
    # random comment
    global x
    # another comment
    size(200, 200)
    x = 42
    print(0 / 0)
```

This is the error message I get:

```
File "<ipython-input-10-b0e58154cf74>", line 9, in _py5_faux_setup
    3    def setup():
 (...)
    5        global x
    6        # another comment
    7        size(200, 200)
    8        x = 42
--> 9        print(0 / 0)

ZeroDivisionError: division by zero
```

Which points to the correct line number.

I think I have everything working now. I also add sensible `global` support for py5bot, even though using the `global` keyword outside of a function is a bit dubious. Not supporting this would potentially lead to other confusing problems for users.

**Comment by hx2A** [comment]
Done! On to the next bug!

**Comment by tabreturn** [comment]
Nice work, @hx2A!
